### ISSUE TITLE
Use jekyll theme for docs

### ISSUE THREAD

**Issue by gekkowrld** [CsqLang/CsqLang.github.io#4]
[suggestion @AniketKumar2500 @WithSJ]
Instead of using html, css, and js, we could just use markdown for the docs and then the rest we can use html.

I do recommend:
- [Time Machine](https://pages-themes.github.io/time-machine/)
- [Modernist](https://pages-themes.github.io/modernist/)
- [Minimal](https://pages-themes.github.io/minimal/)
- [Minima](https://jekyll.github.io/minima/)
- [Leap Day](https://pages-themes.github.io/leap-day/)
- [Hacker](https://pages-themes.github.io/hacker/) #Personal favourite
- [Architect](https://pages-themes.github.io/architect/)

You can look at the full list here:
<https://pages.github.com/themes/>
or use this wiki template <https://github.com/Drassil/git-wiki-skeleton>

**Comment by WithSJ** [comment]
i like Minima (best) and Minimal(2nd best)

**Comment by WithSJ** [comment]
@gekkowrld  You are welcome to update the document

**Comment by gekkowrld** [comment]
[**Preview** @AniketKumar2500 @WithSJ @usmanmusa1920]
I used the template, you can preview it here <https://gekkowrld.me/csq_doc/>
You can give suggestions, changes and concerns before I migrate it to **CSQ**

**Comment by WithSJ** [comment]
great doc

**Comment by usmanmusa1920** [comment]
This is a good suggestion, but it will be good to add the clip board button. for ease!

**Comment by gekkowrld** [comment]
> This is a good suggestion, but it will be good to add the clip board button. for ease!

I can't figure out how to do that. Most of the jekyll theme don't have the feature.

**Comment by AniketKumar2500** [comment]
> [**Preview** @AniketKumar2500 @WithSJ @usmanmusa1920] I used the template, you can preview it here https://gekkowrld.me/csq_doc/ You can give suggestions, changes and concerns before I migrate it to **CSQ**

Really nice.

**Comment by gekkowrld** [comment]
@usmanmusa1920 I have added the `copy` button, @AniketKumar2500, I'm creating a new repository called `docs` to create the docs from, for the current repo `CsqLang.github.io` may be used as homepage and stuff.

**Comment by gekkowrld** [comment]
It is now live here <https://csqlang.github.io/docs/>, anyone who wishes to contribute can now do so.

**Comment by AniketKumar2500** [comment]
@gekkowrld Here add post button is there i would like to know it's actual use.

**Comment by gekkowrld** [comment]
That is a blogging feature, I'll remove it if not needed

**Comment by AniketKumar2500** [comment]
I am having a idea we shall introduce a page where people can ask questions just like in websites of Python, R etc

**Comment by gekkowrld** [comment]
That will involve external hosting, database and other stuff. Not sure if that is necessary for now.

**Comment by usmanmusa1920** [comment]
> @usmanmusa1920 I have added the `copy` button, @AniketKumar2500, I'm creating a new repository called `docs` to create the docs from, for the current repo `CsqLang.github.io` may be used as homepage and stuff.

good and nice

**Comment by usmanmusa1920** [comment]
> That will involve external hosting, database and other stuff. Not sure if that is necessary for now.

yes, let keep on using that email address as for Q/A, or keep on using github issues page as place of such!
